import { Button, HorizontalBox } from "std-widgets.slint";

component HorizontalSplit inherits HorizontalBox {
    padding: 0px;
    spacing: 0px;

    property <length> proportion: self.width / 2;

    left := Rectangle {
        width: proportion;
        Rectangle {
            background: blue;
        }
    }

    handle := Rectangle {
        width: 8px;
        background: @linear-gradient(0deg, #ddd, #aaa);
        TouchArea {
            moved => {
                proportion = parent.x + self.mouse_x;
            }
        }
    }

    right := Rectangle {
        Rectangle {
            background: red;
        }
    }
}

export component AppWindow inherits Window {
    HorizontalSplit { }
}
